name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: npm i -g vercel@canary

      - run: vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}

      - run: |
          VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
          REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }} \
          REDIS_READONLY_TOKEN=${{ secrets.REDIS_READONLY_TOKEN }} \
          pnpm build \

      - run: |
          REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }} \
          REDIS_READONLY_TOKEN=${{ secrets.REDIS_READONLY_TOKEN }} \
          vercel ./ \
          --prod \
          --env REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }} \
          --env REDIS_READONLY_TOKEN=${{ secrets.REDIS_READONLY_TOKEN }} \
          --prebuilt \
          --token ${{ secrets.VERCEL_TOKEN }} \

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
      REDIS_READONLY_TOKEN: ${{ secrets.REDIS_READONLY_TOKEN }}
