name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: npm i -g vercel@canary

      - run: pnpm build

      - run: vercel ./ --yes --prod --token ${{ secrets.VERCEL_TOKEN }}

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
